name: Build MozJPEG on Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build cjpeg.exe on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install NASM
        run: choco install nasm -y
        shell: powershell

      - name: Install vcpkg and dependencies
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install libpng zlib
        shell: powershell

      - name: Create build directory
        run: mkdir build

      - name: Configure with CMake
        run: |
          cd build
          cmake .. ^
            -G "Visual Studio 17 2022" ^
            -A x64 ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
        shell: cmd

      - name: Build project
        run: cmake --build build --config Release
        shell: cmd

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: mozjpeg-windows
          path: |
            build/Release/cjpeg.exe
            build/Release/djpeg.exe
            build/Release/jpegtran.exe
